// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: rider.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rider) Reset() {
	*x = Rider{}
	mi := &file_rider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rider) ProtoMessage() {}

func (x *Rider) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rider.ProtoReflect.Descriptor instead.
func (*Rider) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{0}
}

func (x *Rider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rider) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CreateRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRiderRequest) Reset() {
	*x = CreateRiderRequest{}
	mi := &file_rider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRiderRequest) ProtoMessage() {}

func (x *CreateRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRiderRequest.ProtoReflect.Descriptor instead.
func (*CreateRiderRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRiderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRiderRequest) Reset() {
	*x = ReadRiderRequest{}
	mi := &file_rider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRiderRequest) ProtoMessage() {}

func (x *ReadRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRiderRequest.ProtoReflect.Descriptor instead.
func (*ReadRiderRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRiderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRiderRequest) Reset() {
	*x = UpdateRiderRequest{}
	mi := &file_rider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRiderRequest) ProtoMessage() {}

func (x *UpdateRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRiderRequest.ProtoReflect.Descriptor instead.
func (*UpdateRiderRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRiderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRiderRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_rider_proto protoreflect.FileDescriptor

const file_rider_proto_rawDesc = "" +
	"\n" +
	"\vrider.proto\x12\x04data\"1\n" +
	"\x05Rider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"$\n" +
	"\x12CreateRiderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10ReadRiderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x12UpdateRiderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion2\xac\x01\n" +
	"\fRiderService\x124\n" +
	"\vCreateRider\x12\x18.data.CreateRiderRequest\x1a\v.data.Rider\x120\n" +
	"\tReadRider\x12\x16.data.ReadRiderRequest\x1a\v.data.Rider\x124\n" +
	"\vUpdateRider\x12\x18.data.UpdateRiderRequest\x1a\v.data.RiderB5Z3github.com/dead-letter/dead-letter-data/internal/pbb\x06proto3"

var (
	file_rider_proto_rawDescOnce sync.Once
	file_rider_proto_rawDescData []byte
)

func file_rider_proto_rawDescGZIP() []byte {
	file_rider_proto_rawDescOnce.Do(func() {
		file_rider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)))
	})
	return file_rider_proto_rawDescData
}

var file_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rider_proto_goTypes = []any{
	(*Rider)(nil),              // 0: data.Rider
	(*CreateRiderRequest)(nil), // 1: data.CreateRiderRequest
	(*ReadRiderRequest)(nil),   // 2: data.ReadRiderRequest
	(*UpdateRiderRequest)(nil), // 3: data.UpdateRiderRequest
}
var file_rider_proto_depIdxs = []int32{
	1, // 0: data.RiderService.CreateRider:input_type -> data.CreateRiderRequest
	2, // 1: data.RiderService.ReadRider:input_type -> data.ReadRiderRequest
	3, // 2: data.RiderService.UpdateRider:input_type -> data.UpdateRiderRequest
	0, // 3: data.RiderService.CreateRider:output_type -> data.Rider
	0, // 4: data.RiderService.ReadRider:output_type -> data.Rider
	0, // 5: data.RiderService.UpdateRider:output_type -> data.Rider
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rider_proto_init() }
func file_rider_proto_init() {
	if File_rider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rider_proto_rawDesc), len(file_rider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rider_proto_goTypes,
		DependencyIndexes: file_rider_proto_depIdxs,
		MessageInfos:      file_rider_proto_msgTypes,
	}.Build()
	File_rider_proto = out.File
	file_rider_proto_goTypes = nil
	file_rider_proto_depIdxs = nil
}
